### ISSUE TITLE
craching while starting

### ISSUE THREAD

**Issue by Dikkekip** [cryptii/cryptii#6]
```
events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: this is not a typed array.
    at Function.from (native)
    at /crypty/cryptii/node_modules/gulp-autoprefixer/index.js:25:27
    at run (/crypty/cryptii/node_modules/esdoc/node_modules/core-js/modules/es6.promise.js:89:39)
    at /crypty/cryptii/node_modules/esdoc/node_modules/core-js/modules/es6.promise.js:100:28
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

**Comment by ffraenz** [comment]
Gulp is working fine for me. Make sure you have the correct node version `v6.11.0` installed.

**Comment by Dikkekip** [comment]
fixed it with the old version tnx! keep up the good work


Met Vriendelijke groet,

Maarten Rosier
06-34447304
www.maartenrosier.com
info@maartenrosier.com

2017-07-04 17:30 GMT+02:00 Fränz Friederes <notifications@github.com>:

**Comment by ffraenz** [comment]
Thank you! Will do!
